### PR TITLE
Add find feature, Add rules, development and tests updates

### PR DESCRIPTION
**Pull request by omrilotan**
## Added feature
- Add method `find`: Return respective rule for bot UA matches
- Added rules (crawlers from ["monperrus/crawler-user-agents"](https://github.com/monperrus/crawler-user-agents/))

## Fix
- Fix exclude method not being able to exclude 1st rule (index 0)
- Add Typescript check and apply fixes (see details below) - Address issue #45

## Lots of development upgrades
- Add JSDoc in line documentation
- Add [standardjs](https://standardjs.com/) code linting (opinionated style guide) + CI
  - Apply Auto fix
  - Replace `chai` and `should` with nodejs' native `assert` (getters are recognised as useless expressions)
- Add testing with random user agents using "user-agents"
- Add testing crawlers from ["monperrus/crawler-user-agents"](https://github.com/monperrus/crawler-user-agents/)
  - Add rules accordingly
- Improve tests output: Shorter outputs only print lists of failed tests. See below
- Improve redundant rules check
  - Tells you what rule caught the redundant rule
  - Caught 46 more redundant rules
- Break tests up a bit and move all test files to "tests" directory
- Add assisting files:
  - `.editorconfig` helps text editors conform with style guide
  - `.npmrc` will tell NPM not to create lock file at all

<details>
<summary>Typescript check errors</summary>

```
index.d.ts:25:1 - error TS1036: Statements are not allowed in ambient contexts.

25 testUserAgent.extend = extend;
   ~~~~~~~~~~~~~
```

</details>

<details>
<summary>Example for passing test results</summary>

```
  Features
    isbot
      ✓ should always return a boolean
    isbot.extend
      ✓ should not detect (Mozilla/5.0) as bot
      ✓ should detect (Mozilla/5.0) as bot
    isbot.exclude
      ✓ should detect Cubot as bot
      ✓ should not detect Cubot as bot
      ✓ should detect Googlebot, but not Cubot (use case)
    isbot.find
      ✓ should return null for non bot browser
      ✓ should return the rule used to identify as bot

  Test user-agent fixtures
    Legit user agent strings
      ✓ Should return false for 5989 user agent strings
    Known crawler user agent strings
      ✓ Should return true for 3164 user agent strings
    Imported known crawler user agent strings
      ✓ Should return true for 880 user agent strings
    Random legit user agents
      ✓ should return false for 203 random user agent strings

  Check for redundant crawler rules
    ✓ should include 862 non redundant rules (6859ms)


  13 passing (7s)
```

</details>

<details>
<summary>Example for errors list in test results</summary>

```
  1) redundant crawler rules should include 856 non redundant rules:
     Error: Found 47 rules which include redundant strings:
 - "validator" matched with rule "ida"
 - "therarestparser/" matched with rule "parse"
 - "spyder" matched with rule "spy"
 - "spida/" matched with rule "ida"
 - "site[-\s]?scan" matched with rule "scan"
 - "site[-\s]?check" matched with rule "check"
 - "RetrevoPageAnalyzer" matched with rule "Analyzer"
 - "Qseero" matched with rule "seer"
 - "privacyfinder/" matched with rule "finder"
 - "Page Analyzer" matched with rule "Analyzer"
 - "NutchCVS" matched with rule "Nutch"
 - "mygetright/" matched with rule "getright/"
 - "MFHttpScan" matched with rule "Scan"
 - "MetaProducts Download Express" matched with rule "Download Express"
 - "MegaIndex\.ru" matched with rule "Index"
 - "Mac Finder" matched with rule "Finder"
 - "linksweeper/" matched with rule "sweep"
 - "linkscan/x\.x" matched with rule "linkscan/"
 - "linkscan/" matched with rule "scan"
 - "links?\s?check" matched with rule "check"
 - "linklint-checkonly/" matched with rule "check"
 - "link check" matched with rule "link check"
 - "lecodechecker/" matched with rule "check"
 - "jchecklinks/" matched with rule "check"
 - "igetter/" matched with rule "getter"
 - "igdeSpyder" matched with rule "Spyder"
 - "http://ozysoftware\.com/index\.html" matched with rule "index"
 - "htmlparser/" matched with rule "parse"
 - "genderanalyzer" matched with rule "analyzer"
 - "FindLinks" matched with rule "FindLink"
 - "favcollector/" matched with rule "collect"
 - "Extreme Picture Finder" matched with rule "Finder"
 - "ExtractorPro" matched with rule "Extract"
 - "europarchive\.org" matched with rule "archive"
 - "ec2linkfinder" matched with rule "finder"
 - "DNS-Tools Header-Analyzer" matched with rule "Analyzer"
 - "del\.icio\.us-thumbnails/" matched with rule "thumb"
 - "CheckWeb" matched with rule "Check"
 - "checklinks/" matched with rule "check"
 - "Butterfly/" matched with rule "Butterfly"
 - "BStop\.BravoBrian\.it Agent Detector" matched with rule "BravoBrian"
 - "bpimagewalker/" matched with rule "imagewalker/"
 - "bloglines-images/" matched with rule "images"
 - "archive-com" matched with rule "archive"
 - "Aberja Checkomat" matched with rule "Check"
 - "A6-Indexer" matched with rule "Index"
 - "!Susie" matched with rule "!Susie"
```

</details>

### CODE REVIEW

**Comment by omrilotan** [comment]
@gorangajic could you disable Semaphore integration?

**Comment by gorangajic** [comment]
done

**Comment by omrilotan** [comment]
@gorangajic Sorry for the large PR. Would you be interested in publishing this update?

**Comment by maximn** [comment]
Hi, any ETA for this to be merged? 
I'm waiting for this one `Add Typescript check and apply fixes (see details below) - Address issue #45`

**Comment by maximn** [comment]
@gorangajic awesome! When are you going to release it?

**Comment by gorangajic** [comment]
@omrilotan do you want to do a release?

**Comment by omrilotan** [comment]
@gorangajic Yes but I'm not a collaborator on NPM

**Comment by gorangajic** [comment]
Can you check because I gave you access

**Comment by omrilotan** [comment]
(`npm access grant read-write omrilotan isbot`)

**Comment by gorangajic** [comment]
Screenshot 2019-10-30 at 11 36 22

**Comment by omrilotan** [comment]
Published! Thank you!

**Comment by gorangajic** [comment]
Thank you!

**Pull request merged**
